<?php

namespace Comment\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     *
     * @param int $num
     * @return array
     */
    public function findLatest( $num )
    {
        $qb = $this->getQueryBuilder()
            ->orderBy('c.createdAt', 'desc')
            ->setMaxResults( $num );

        return $qb->getQuery()->getResult();
    }
    
    /**
     *
     * @param int $object
     * @return array
     */
    public function countObjectComments( $object )
    {
        $qb = $this->getQueryBuilder()
            ->select('count(c)')
            ->where( 'c.comment_object = :object')
            ->setParameter( 'object', $object )
        ;

        return $qb->getQuery()->getSingleScalarResult();
    }
    
    /**
     * Return the first post
     * @return Author
     */
    public function findFirst()
    {
        $qb = $this->getQueryBuilder()
            ->orderBy('c.id', 'asc')
            ->setMaxResults( 1 );

        return $qb->getQuery()->getSingleResult();
    }
    
    /**
     * Return the first post
     * @return Author
     */
    public function findLast()
    {
        $qb = $this->getQueryBuilder()
            ->orderBy('c.id', 'desc')
            ->setMaxResults( 1 );

        return $qb->getQuery()->getSingleResult();
    }

    /**
     *
     * @param boolen $indexed - проиндексировать массив по id
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function getQueryBuilder( $indexed = false )
    {
        $builder = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('c');
        if( $indexed )
            $builder->from( $this->getClassName(), 'c', 'c.id');
        else
            $builder->from( $this->getClassName(), 'c');

        return $builder;

    }
}
