fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /
    
