NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc/%comment_api.version%

comment_api:
    resource: "@CommentApiBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api/%comment_api.version%

comment_core:
    resource: "@CommentCoreBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /
    
