parameters:
#    blog_test.example.class: Blog\TestBundle\Example

services:
#    blog_test.example:
#        class: %blog_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
