<?php

namespace Blog\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     *
     * @param int $num
     * @return array
     */
    public function findLatest( $num )
    {
        $qb = $this->getQueryBuilder()
            ->orderBy('p.createdAt', 'desc')
            ->setMaxResults( $num );

        return $qb->getQuery()->getResult();
    }

    /**
     * Return the first post
     * @return Post
     */
    public function findFirst()
    {
        $qb = $this->getQueryBuilder()
            ->orderBy('p.id', 'asc')
            ->setMaxResults( 1 );

        return $qb->getQuery()->getSingleResult();
    }

    /**
     *
     * @param boolen $indexed - проиндексировать массив по id
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function getQueryBuilder( $indexed = false )
    {
        $builder = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p');
        if( $indexed )
            $builder->from( $this->getClassName(), 'p', 'p.id');
        else
            $builder->from( $this->getClassName(), 'p');

        return $builder;

    }
}
