parameters:
    post.dynamic_relation.subscriber.class: Blog\ModelBundle\EventListner\DynamicRelationSubscriber

services:
    post.dynamic_relation.subscriber:
        class: %post.dynamic_relation.subscriber.class%
        arguments:
            - %comment_resolve_class%
            - @blog.core.bundle_resolver
        tags:
            - { name: doctrine.event_subscriber, connection: default }