parameters:
    comment.manager.class: Comment\CoreBundle\Services\Manager
    comment.twig_extension.class: Comment\CoreBundle\TwigExtension\CommentExtension
    
services:
    comment.manager:
        class: %comment.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
            - @security.context
            - @security.acl.provider
            - @comment.model.comment_type
            - %doctrine_resolve_class%
            
    comment.twig_extension:
        class: %comment.twig_extension.class%
        arguments:
            - @fragment.handler
        tags:
            - { name: twig.extension }