parameters:
    blog.core.twig.plural_extension.class:  Blog\CoreBundle\TwigExtension\TransPlural
    blog.core.author_manager.class:         Blog\CoreBundle\Services\AuthorManager
    blog.core.post_manager.class:           Blog\CoreBundle\Services\PostManager
    blog.core.bundle_resolver.class:        Blog\CoreBundle\Services\BundleResolver

services:
    acme.twig.acme_extension:
        class: %blog.core.twig.plural_extension.class%
        arguments: [@translator]
        tags:
            - { name: twig.extension }

    blog.core.author_manager:
        class: %blog.core.author_manager.class%
        arguments:
            - @doctrine.orm.entity_manager

    blog.core.post_manager:
        class: %blog.core.post_manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
            - @security.context
            - @security.acl.provider
            
    blog.core.bundle_resolver:
        class: %blog.core.bundle_resolver.class%
        arguments:
            - %kernel.bundles%